#!/usr/bin/env bash

set -eu

outdir="output/pe_mapping"
if [[ ! -e "${outdir}" ]]; then
    mkdir -p "${outdir}"
fi

samtools=bin/samtools/samtools

main_genome="output/genomes/wolbachia_all.fasta"
my_main_genome="${outdir}/ref.fasta"
alt_idx="output/genomes/wolbachia_all.alt"
my_alt_idx="${outdir}/ref.fasta.alt"

pe_reads="data/Mh_filtered_trimmed.fastq.gz"
bwa_log="${outdir}/bwamem.log"
samtools_log="${outdir}/samtools.log"
mapped_reads_only="${outdir}/pe_mapped_filtered.bam"
output_bam="${outdir}/pe_mapped.bam"

printf "[ %s: Running bwa index ]\n" "$(date)"
cp "${main_genome}" "${my_main_genome}"
cp "${alt_idx}" "${my_alt_idx}"
bwa index "${my_main_genome}"

printf "[ %s: Running bwa mem ]\n" "$(date)"
printf "[ %s: Filtering mapping results ]\n" "$(date)"
bwa mem \
    -t 50 \
    -p \
    "${my_main_genome}" \
    "${pe_reads}" \
    2> "${bwa_log}" \
    | "${samtools}" view \
    --threads 50 \
    -F 12 \
    -b -o "${mapped_reads_only}"

printf "[ %s: Running samtools sort ]\n" "$(date)"
"${samtools}" sort \
    -@ 50 \
    -m 7G \
    -l 9 \
    -o "${output_bam}" \
    "${mapped_reads_only}" \
    2> "${samtools_log}"

printf "[ %s: Running samtools index ]\n" "$(date)"
"${samtools}" index "${output_bam}"

printf "[ %s: Removing temporary samfile %s ]\n" \
    "$(date)" "${mapped_reads_only}"
rm "${mapped_reads_only}"

exit 0
