#!/usr/bin/env bash

set -eu

outdir="output/pe_mapping"
if [[ ! -e "${outdir}" ]]; then
    mkdir -p "${outdir}"
fi

samtools=bin/samtools/samtools

main_genome="output/genomes/wolbachia_all.fasta"
my_main_genome="${outdir}/ref.fasta"
alt_idx="output/genomes/wolbachia_all.alt"
my_alt_idx="${outdir}/ref.fasta.alt"

pe_reads="data/pe_merged.fastq.gz"
bwa_log="${outdir}/bwamem.log"
samtools_log="${outdir}/samtools.log"
unsorted_sam="${outdir}/pe_mapped_unsorted.sam"
output_bam="${outdir}/pe_mapped.bam"

printf "[ %s: Running bwa index ]\n" "$(date)"
cp "${main_genome}" "${my_main_genome}"
cp "${alt_idx}" "${my_alt_idx}"
bwa index "${my_main_genome}"

printf "[ %s: Running bwa mem ]\n" "$(date)"
bwa mem \
    -t 100 \
    -p \
    "${my_main_genome}" \
    "${pe_reads}" \
    > "${unsorted_sam}" \
    2> "${bwa_log}"

printf "[ %s: Running samtools sort ]\n" "$(date)"
"${samtools}" sort \
    -@ 50 \
    -m 7G \
    -l 9 \
    -o "${output_bam}" \
    "${unsorted_sam}" \
    2> "${samtools_log}"

printf "[ %s: Running samtools index ]\n" "$(date)"
"${samtools}" index "${output_bam}"

printf "[ %s: Removing temporary samfile %s ]\n" "$(date)" "${unsorted_sam}"
rm "${unsorted_sam}"

exit 0
